//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeetUp.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int AppointmentId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> FromEmployeeId { get; set; }
        public Nullable<int> ToEmployeeId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> FromTime { get; set; }
        public Nullable<System.TimeSpan> ToTime { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> StatusId { get; set; }
    
        public virtual EmployeeDetail EmployeeDetail { get; set; }
        public virtual Status Status { get; set; }
        public virtual EmployeeDetail EmployeeDetail1 { get; set; }
    }
}
