//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeetUp.Entites
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Login
    {
        public int LoginId { get; set; }
        [Required(ErrorMessage = "Employee ID cannot be left blank!!!")]
        public Nullable<int> EmployeeId { get; set; }
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Password cannot be left blank!!!")]
        public string Password { get; set; }
        public string LoginErrorMessage { get; set; }
        public virtual EmployeeDetail EmployeeDetail { get; set; }
    }
}
